package it.polito.loginservice.security

import io.jsonwebtoken.Claims
import io.jsonwebtoken.ExpiredJwtException
import io.jsonwebtoken.Jwts
import io.jsonwebtoken.security.Keys
import org.springframework.beans.factory.annotation.Value
import org.springframework.security.authentication.AuthenticationServiceException
import org.springframework.stereotype.Component
import java.lang.NullPointerException
import javax.xml.bind.ValidationException

@Component
class JwtUtils {

    @Value("\${key}")
    lateinit var key: String

    @Value("\${prefix}")
    lateinit var prefix : String

    /*
        it validates the token received in a
        request, catching all exceptions and returning true only if the token is valid
     */
    fun validateJwt(authToken: String): Boolean {
        if(authToken.isEmpty())
            throw ValidationException("Token should not be empty")
        try {
            val claims: Claims = Jwts.parserBuilder()
                .setSigningKey(Keys.hmacShaKeyFor(key.toByteArray()))
                .build()
                 .parseClaimsJws(authToken.replace(prefix, ""))
                .getBody()

            return true
        } catch (e: ExpiredJwtException) {
            throw AuthenticationServiceException("token expired: please login again")
        } catch (e: NullPointerException) {
            throw AuthenticationServiceException("token generated by invalid key")
        }
        catch (e: Exception) {
            throw AuthenticationServiceException(e.message)
        }
    }

    /*
        it relies on the Jwts
        parser to retrieve the username and roles from the token
     */
    fun getDetailsJwt(authToken: String): Map<String, Any> {
        if(authToken.isEmpty())
            throw ValidationException("Token should not be empty")
        try {
            val claims = Jwts.parserBuilder()
                    .setSigningKey(Keys.hmacShaKeyFor(key.toByteArray()))
                    .build()
                    .parseClaimsJws(authToken.replace(prefix, ""))

            val scopes = claims.body["roles"] as ArrayList<String>
            val authorities = claims.body["authorities"] as ArrayList<String>
            //val scope = scopes.get(0)

            val username = claims.body.subject
            //val role = scope
            return mapOf("username" to username, "roles" to scopes, "authorities" to authorities)

        } catch (e: ExpiredJwtException) {
            throw AuthenticationServiceException("token expired: please login again")
        }catch (e: Exception) {
            throw Exception(e.message)
        }

    }
}